

services:
  db:
    image: postgres:15
    container_name: personance_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: personance_db
    ports:
      - "5433:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - personance-network
    restart: always

volumes:
  postgres_data:

networks:
  personance-network:
